### ISSUE TITLE
Removal of doc/ folder

### ISSUE THREAD

**Issue by sarelvdwalt** [afrihost/swarm-process#15]
@mostertb and @johnathanmdell I propose we remove the doc/ folder. My current opinion of it is it's largely useless, won't get kept up to date and bloating the library. What do you say, yes/no?

**Comment by mostertb** [comment]
Im happy with that 👍 

The `README.md` and `/examples` folder effectively supersede the automatically generated docs

**Comment by sarelvdwalt** [comment]
done.
