### ISSUE TITLE
Max Job Runtime

### ISSUE THREAD

**Issue by cjsfj** [afrihost/swarm-process#3]
Sometimes we prefer to cap the runtime of a job (at say, 30 min) to kill it if it runs too long. Is there any way to do that with this package?

**Comment by sarelvdwalt** [comment]
Hey @cjsfj - no there isn't a way currently to do this. But it's a great suggestion - I'm sure lots of users would find a feature like that useful. Are you interested in sending me a pull request with a code change suggestion?

**Comment by sarelvdwalt** [comment]
@cjsfj Please see PR #13 - it will address what your requirement is here. I will therefore close this. If you feel it does not, you are welcome to chat to me and we'll look into it more.

**Comment by cjsfj** [comment]
thank you!
